//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Blog
    {
        public Blog()
        {
            this.Posts = new ObservableCollection<Post>();
        }
    
        public int BlogId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
    
        public virtual ObservableCollection<Post> Posts { get; set; }
    }
}
